CREATE TABLE USERS(
	ID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(10),
	JDATE DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE USERPROFILE(
	ID SERIAL PRIMARY KEY REFERENCES USERS ON DELETE CASCADE,
	NICKNAME VARCHAR(20) NOT NULL,
	TWEETS INTEGER DEFAULT 0,
	FOLLOWING INTEGER DEFAULT 0,
	FOLLOWERS INTEGER DEFAULT 0,
	LIKES INTEGER DEFAULT 0,
	BIO VARCHAR(100)
);

CREATE TABLE TWEETS(
	TWEETID SERIAL PRIMARY KEY NOT NULL,
	USERID INT NOT NULL,
	TITLE CHAR(20) NOT NULL,
	CONTEXT CHAR(140) NOT NULL
	TTIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MESSAGES(
	MESSAGEID SERIAL PRIMARY KEY,
	SENDERID INTEGER REFERENCES USERPROFILE (ID) ON DELETE SET NULL,
	RECIEVERID INTEGER REFERENCES USERPROFILE (ID) ON DELETE SET NULL,
	CONTENT VARCHAR(100) NOT NULL,
	SENT BOOLEAN DEFAULT FALSE,
	MTIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE USERINFO(
	USERID SERIAL PRIMARY KEY NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE,
	NAME VARCHAR(20) NOT NULL,
	SURNAME VARCHAR(20) NOT NULL,
	NICKNAME VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(25) NOT NULL,
	LANGUAGE VARCHAR(20) NOT NULL
);

CREATE TABLE LISTS(
	LISTID SERIAL PRIMARY KEY,
	SUBSCRIBERS INTEGER DEFAULT 0,
	MEMBERS INTEGER DEFAULT 0,
	NAME VARCHAR(30) NOT NULL,
	CREATORID INTEGER NOT NULL REFERENCES USERPROFILE (ID) ON DELETE CASCADE
);

CREATE TABLE LISTMEMBERS(
	LISTID INTEGER NOT NULL REFERENCES LISTS(LISTID) ON DELETE CASCADE,
	USERID INTEGER NOT NULL REFERENCES USERPROFILE(ID) ON DELETE CASCADE,
	USERTYPE VARCHAR(15) NOT NULL,
	PRIMARY KEY(LISTID,USERID)
);

CREATE TABLE LIKES(
	USERID INTEGER NOT NULL REFERENCES USERPROFILE(ID) ON DELETE CASCADE,
	TWEETID INTEGER NOT NULL REFERENCES TWEETS(TWEETID) ON DELETE CASCADE,
	PRIMARY KEY(USERID,TWEETID),
	LikeTIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE REZWEET(
	USERID INTEGER NOT NULL REFERENCES USERPROFILE(ID) ON DELETE CASCADE,
	TWEETID INTEGER NOT NULL REFERENCES TWEETS(TWEETID) ON DELETE CASCADE,
	PRIMARY KEY(USERID,TWEETID),
	RZTIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);



INSERT INTO USERS (USERNAME, PASSWORD) VALUES(
	'cetineremre',
	'123456'
);

INSERT INTO USERPROFILE (NICKNAME, BIO) VALUES(
	'cetineremre',
	'Istanbul 23'
);

INSERT INTO TWEETS (USERID, TITLE, CONTEXT) VALUES(
	1,
	'Admin Tweets',
	'First Tweet By Adminssss'
);

INSERT INTO MESSAGES(SENDERID,RECIEVERID, CONTENT) VALUES(
	1,
	1,
	'Good afternoon'
);



INSERT INTO USERINFO (NAME, SURNAME, NICKNAME, EMAIL, LANGUAGE) VALUES(
	'Lucifer',
	'Morningstar',
	'Mr. Morningstar',
	'morningstar@inferno.com',
	'English'
);

INSERT INTO LISTS (NAME,CREATORID) VALUES(
	'First List',
	1
);

INSERT INTO LISTMEMBERS(LISTID,USERID,USERTYPE) VALUES (
    1,
    1,
    'owner'
);

INSERT INTO LIKES(USERID,TWEETID) VALUES(
     1,
     1
);

INSERT INTO REZWEET(USERID,TWEETID) VALUES(
     1,
     1
);

