CREATE TABLE TWEETS(
	TWEETID SERIAL PRIMARY KEY NOT NULL,
	USERID INT NOT NULL,
	TITLE CHAR(20) NOT NULL,
	CONTEXT CHAR(140) NOT NULL
);

INSERT INTO TWEETS (USERID, TITLE, CONTEXT) VALUES(
	1,
	'Admin Tweets',
	'First Tweet By Adminssss'
);